GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts
content-type: application/json

{
    "text": "test",
    "username": "username",
    "image": "https://i.pinimg.com/564x/0b/40/ff/0b40ffb7cfdbba25578341e3df689d30.jpg"
}


###
DELETE http://localhost:3000/api/posts/64eed7187a9a1e76fdf746ec

###

PUT http://localhost:3000/api/posts/64eed7187a9a1e76fdf746ec
content-type: application/json

{
    "text": "test11"
}

###
GET http://localhost:3000/api/comments?postID=64f02ac0442d170e2838e41f

### 

POST http://localhost:3000/api/comments
content-type: application/json

{
    "text": "test",
    "username": "username"
}

###

PUT http://localhost:3000/api/comments/64f02ac0442d170e2838e41f
content-type: application/json

{
    "text": "test12"
  
}